### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by schrodyn** [danielplohmann/smda#49]
Spotted this error while submitting files with MCRIT in dir mode and wanted to report it. File hash f3af394d9c3f68dff50b467340ca59a11a14a3d56361e6cffd1cf2312a7028ad

```
0.001s -> (architecture: intel.32bit, base_addr: 0x00000000): 0 functions
ERROR: SMDA caused an exception while processing this file: Samples/f3af394d9c3f68dff50b467340ca59a11a14a3d56361e6cffd1cf2312a7028ad
Traceback (most recent call last):
  File "/usr/home/schrodinger/.local/src/mcrit/mcrit/client/McritConsole.py", line 109, in getSmdaReportFromFilepath
    smda_report = disassembler.disassembleFile(filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schrodinger/.venv/mcrit/lib/python3.11/site-packages/smda/Disassembler.py", line 42, in disassembleFile
    loader = FileLoader(file_path, map_file=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schrodinger/.venv/mcrit/lib/python3.11/site-packages/smda/utility/FileLoader.py", line 22, in __init__
    self._loadFile()
  File "/home/schrodinger/.venv/mcrit/lib/python3.11/site-packages/smda/utility/FileLoader.py", line 36, in _loadFile
    self._data = loader.mapBinary(self._raw_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/schrodinger/.venv/mcrit/lib/python3.11/site-packages/smda/utility/ElfFileLoader.py", line 97, in mapBinary
    mapped_binary = bytearray(align(virtual_size, 0x1000))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by danielplohmann** [comment]
thanks again for reporting, fixed in v1.13.9.
